### ISSUE TITLE
Наименование переменных

### ISSUE THREAD

**Issue by khda91** [pkev321/cinemaTheater#1]
https://github.com/pkev321/cinemaTheater/blob/0c8d68a9acb218e1f3d72e1c962ad14e3e506304/src/ru/levelup/java/cinema/theater/CinemaTheater.java#L24

Если в коде без описания типа переменной найти её, будет больше понятно что это скорее всего какое-то главное меню, а не меню связанное с едой

**Comment by pkev321** [comment]
Согласен, внёс изменения

**Comment by khda91** [comment]
closed
